name: digital_receipt
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_slidable:
  http:
<<<<<<< HEAD
  sqflite:
  path_provider:
  path:
<<<<<<< HEAD
  dio:
  fluttertoast:
  device_info:
  flutter_email_sender:
  firebase_core:
  firebase_auth:
  firebase_messaging:
  flutter_device_type:
  shared_preferences:
  overlay_support:
  cupertino_icons:
  share:
  carousel_pro:
  carousel_slider:
  font_awesome_flutter:
  flutter_mailer:
  flutter_svg:
  image_picker:
  permission_handler:
  wc_form_validators:
  keyboard_actions:
  pin_code_text_field:
  pin_code_fields:
  flare_flutter:
  url_launcher:
  random_color:
  device_preview:
  number_display:
=======
=======
  sqflite: ^1.3.1
  path_provider: ^1.6.11
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 25bd565d7172d23b0b1103b6e36745551a84e7e5
=======

  path: ^1.7.0

>>>>>>> 992b36d703de62dc8805936dba2ecfc148e39776
=======
>>>>>>> 31ac62768aaf319e6e17773cb7dde14404903de6
  dio: ^3.0.9
  fluttertoast: ^4.0.1
  device_info: ^0.4.2+4
  flutter_email_sender: ^3.0.1
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  firebase_messaging: ^6.0.16
  flutter_device_type: ^0.2.0
  shared_preferences: ^0.5.7+3
  cupertino_icons: ^0.1.3
  carousel_slider: ^2.1.0
  flutter_mailer: ^0.5.1
  currency_pickers: ^1.0.6
  contacts_service: ^0.4.6

  flutter_svg: ^0.17.4

  flutter_country_picker: ^0.1.6

  image_picker: ^0.6.7+2
  permission_handler: ^5.0.1+1
  wc_form_validators: ^0.1.1
  pin_code_fields: ^3.1.2
  package_info: ^0.4.1
  url_launcher: ^5.4.11
  random_color: ^1.0.5
  device_preview: ^0.4.5
<<<<<<< HEAD
  number_display: ^2.3.0
>>>>>>> d34dcae660ea6336ad92f89ee53d4939b6d93ad6
  data_connection_checker: 

  hive:
  hive_flutter:
  google_sign_in:
=======
  flutter_local_notifications: ^1.4.4+2
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  google_sign_in: ^4.5.1
  flutter_colorpicker: ^0.3.4
  rxdart: ^0.24.1
<<<<<<< HEAD
>>>>>>> 25bd565d7172d23b0b1103b6e36745551a84e7e5








# TO Generate PDF file
  pdf:
  flutter_full_pdf_viewer:
  esys_flutter_share:

<<<<<<< HEAD
  provider:
  connectivity:
  intl:
=======
=======
  in_app_purchase: any
  signature: any
# TO Generate PDF file
  theme_provider: ^0.4.0+1

  pdf: ^1.9.0
  flutter_full_pdf_viewer: ^1.0.6
  esys_flutter_share: ^1.0.2

>>>>>>> 31ac62768aaf319e6e17773cb7dde14404903de6
  provider: ^4.1.3
  intl: ^0.16.1
>>>>>>> 25bd565d7172d23b0b1103b6e36745551a84e7e5

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: any
  build_runner: any
  quiver: any
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/logos/
    - assets/BACKGROUND.jpg
    - assets/gmail.png
    - assets/images/
      # For receipt generation
    - assets/fonts/Montserrat/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MuseoModerno
      fonts:
        - asset: assets/fonts/MuseoModerno/static/MuseoModerno-Regular.ttf
          weight: 700

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 700

    - family: Southampton
      fonts:
        - asset: assets/fonts/Southampton/Southampton.ttf
          # weight: 700

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
